workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS simulator (no codesign)
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/Runner.app

    publishing:
      email:
        recipients:
          - pandeyeklavya35@gmail.com
        notify:
          success: true
          failure: true
